
language: c

compiler:
  - gcc

cache:
  apt: true
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55/cmake-3.x
    packages:
    - gcc-6
    - g++-6
    - libboost-dev
    - gcc-multilib
    - gcc-6-multilib
    - g++-multilib
    - g++-6-multilib
    - libc6-dev-i386
    - libc6-i386
    - cxxtest
    - cmake

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
before_script:
  - cmake --version
  
script: 
  - make all

sudo: false
dist: trusty
